[tool.poetry]
name = "vumi2"
version = "0.0.1"
description = "Vumi, but with Python3 and Trio async"
authors = ["Praekelt.org <dev@praekelt.org>"]
license = "BSD 3-Clause"
readme = "README.md"
packages = [
    { include = "vumi2", from = "src" }
]
include = [
    { path = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.7"
trio = "^0.20.0"
async-amqp = "^0.5.0"
attrs = "^21.4.0"
cattrs = "^22.1.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
mypy = "^0.950"
flake8 = "^4.0.1"
pytest-trio = "^0.7.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
preview = true

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
trio_mode = true
addopts = "--cov=src"
